version: '3.7'

services:

  nproxy:
    image: t3kit/nproxy:1.1.1
    container_name: nproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/.certs/server:/etc/nginx/certs
    networks:
      - nproxy
    restart: unless-stopped

networks:
  nproxy:
    name: nproxy
