version: '3.7'

services:

  nproxy:
    image: t3kit/nproxy:1.2.0
    container_name: nproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/.certs/server:/etc/nginx/certs
      - dhparam:/etc/nginx/dhparam
    networks:
      - nproxy
    restart: unless-stopped

networks:
  nproxy:
    name: nproxy

volumes:
  dhparam:
    name: nproxy_dhparam
